MSTR-368: pytest code refactoring
SW13-Monstera/AI-server pull request #11
Opened 2022-11-09 06:56 UTC by ekzm8523

### Issue Number

close: #MSTR-368

### 작업 내역

> 구현 내용 및 작업 했던 내역

- [x] pyrootlib를 추가하여 모든 path의 root를 고정하였습니다.
- [x] pytest fixture에 테스팅용 데이터를 불러오는 부분을 전부 Factory 형태로 리팩토링 하였습니다. 

### 변경사항

- 의존성 목록

### 작업 유형

- [ ] 신규 기능 추가
- [ ] 버그 수정
- [x] 리펙토링
- [ ] 문서 업데이트

### PR 특이 사항

> PR을 볼 때 주의깊게 봐야하거나 말하고 싶은 점

- 이전 코드에서 기능이 변경되지는 않았고 최대한 중복 코드를 줄이려 노력하였습니다 😊

2022-11-09 15:44 UTC, kshired commented
@ekzm8523 리팩토링은 잘하셨을거라 믿고..
codecov 에 tests 아래 파일들도 coverage에 같이 잡혀서 커버리지가 낮게 나오는 것 같아요.
이 부분 해소해보심 좋을듯

2022-11-09 15:45 UTC, kshired requested changes
코멘트 참고

2022-11-10 03:15 UTC, ekzm8523 commented
> 

dd

2022-11-10 09:20 UTC, ekzm8523 commented
> 코멘트 참고

@kshired codecov 설정을 변경하여 70% 이상일때는 경고표시가 나지 않도록 설정했어요!!
코멘트 남겨주신 tests 무시하라는 옵션도 추가하였습니다 😊

2022-11-10 13:12 UTC, kshired approved these changes

2022-11-10 15:33 UTC, merged